---
processes:
- name: confluent-server
  executable: /var/vcap/jobs/confluent-server/bin/ctl
  args: [start]
  ephemeral_disk: true
  persistent_disk: true
  env: {}
  limits:
    memory: 1G
    open_files: 1024
  hooks:
    pre_start: /var/vcap/jobs/confluent-server/bin/bpm-pre-start
# example at https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/bpm-test-agent/templates/bpm.yml.erb
