---
name: confluent-platform
addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

variables:
- name: keystore-password
  type: password
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: "Confluent Certificate Authority"
- name: confluent-server-tls
  type: certificate
  options:
    ca: ca
    common_name: "*.((confluent-server-external-host))"
- name: confluent-connect-tls
  type: certificate
  options:
    ca: ca
    common_name: "*.((confluent-connect-external-host))"
- name: confluent-schema-registry-tls
  type: certificate
  options:
    ca: ca
    common_name: "*.((confluent-schema-registry-external-host))"
- name: confluent-control-center-tls
  type: certificate
  options:
    ca: ca
    common_name: "*.((confluent-control-center-external-host))"
- name: confluent-ksql-tls
  type: certificate
  options:
    ca: ca
    common_name: "*.((confluent-ksql-external-host))"
- name: server-jaas-password
  type: password
- name: metric-jaas-password
  type: password
- name: connect-kafka-jaas-password
  type: password
- name: control-center-kafka-jaas-password
  type: password
- name: basic-jaas-password
  type: password
- name: schema-registry-users-connect-password
  type: password
- name: schema-registry-users-ksql-password
  type: password
- name: schema-registry-users-app-password
  type: password
- name: ksql-kafka-jaas-password
  type: password
- name: schema-registry-jaas-password
  type: password
- name: ksql-users-developer-password
  type: password

instance_groups:
- name: confluent-zookeeper
  azs: [z1, z2, z3]
  instances: 3
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  jobs:
  - name: confluent-zookeeper
    release: confluent-platform
    properties:
      jaas:
        users:
          server:
            username: server
            password: ((server-jaas-password))
          metric:
            username: metric
            password: ((metric-jaas-password))
          connect:
            username: connect
            password: ((connect-kafka-jaas-password))
          control-center:
            username: control-center
            password: ((control-center-kafka-jaas-password))
          ksql:
            username: ksql
            password: ((ksql-kafka-jaas-password))
          schema-registry:
            username: schema-registry
            password: ((schema-registry-jaas-password))
- name: confluent-server
  azs: [z1, z2, z3]
  instances: 3
  vm_type: default
  stemcell: default
  persistent_disk: 200_000
  networks:
  - name: default
  jobs:
  - name: confluent-server
    release: confluent-platform
    properties:
      tls:
        ca_certs:
        - ((ca.certificate))
        certificate: ((confluent-server-tls))
      keystore_password: ((keystore-password))
      jaas:
        username: server
        password: ((server-jaas-password))
      metric:
        jaas:
          username: metric
          password: ((metric-jaas-password))
- name: confluent-control-center
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  vm_extensions:
  - control-center 
  networks:
  - name: default
  jobs:
  - name: confluent-control-center
    release: confluent-platform
    properties:
      tls:
        ca_certs:
        - ((ca.certificate))
        certificate: ((confluent-control-center-tls))
      keystore_password: ((keystore-password))
      kafka:
        jaas:
          username: control-center
          password: ((control-center-kafka-jaas-password))
      basic:
        jaas:
          username: admin
          password: ((basic-jaas-password))
- name: confluent-schema-registry
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  jobs:
  - name: confluent-schema-registry
    release: confluent-platform
    properties:
      debug: true
      tls:
        ca_certs:
        - ((ca.certificate))
        certificate: ((confluent-schema-registry-tls))
      keystore_password: ((keystore-password))
      kafka:
        jaas:
          username: schema-registry
          password: ((schema-registry-jaas-password))
      users:
        admin:
          username: admin
          password: ((basic-jaas-password))
          roles:
          - admin
          - app
        connect:
          username: connect
          password: ((schema-registry-users-connect-password))
          roles:
          - admin
          - app
        ksql:
          username: ksql
          password: ((schema-registry-users-ksql-password))
          roles:
          - admin
          - app
        app:
          username: user
          password: ((schema-registry-users-app-password))
          roles:
          - app
- name: confluent-connect
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  jobs:
  - name: confluent-connect
    release: confluent-platform
    properties:
      tls:
        ca_certs:
        - ((ca.certificate))
        certificate: ((confluent-connect-tls))
      keystore_password: ((keystore-password))
      basic:
        jaas:
          username: admin
          password: ((basic-jaas-password))
      kafka:
        jaas:
          username: connect
          password: ((connect-kafka-jaas-password))
      schema_registry:
        basic:
          username: connect
          password: ((schema-registry-users-connect-password))
      connectors:
        s3:
          endpoint: ((connectors-s3-endpoint))
          access_key: ((connectors-s3-access-key))
          secret_key: ((connectors-s3-secret-key))
          bucket: ((connectors-s3-bucket))
- name: confluent-ksql
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  vm_extensions:
  - ksql
  networks:
  - name: default
  jobs:
  - name: confluent-ksql
    release: confluent-platform
    properties:
      external_hostname: ((ksql-external-hostname))
      tls:
        ca_certs:
        - ((ca.certificate))
        certificate: ((confluent-ksql-tls))
      keystore_password: ((keystore-password))
      kafka:
        jaas:
          username: ksql
          password: ((ksql-kafka-jaas-password))
      users:
        admin:
          username: admin
          password: ((basic-jaas-password))
          roles:
          - admin
          - developer
          - user
          - ksq-user
        developer:
          username: developer
          password: ((ksql-users-developer-password))
          roles:
          - developer
          - user

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 315.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 12142ca9437e48694374876fe0236938e252d1e2
  stemcell:
    os: ubuntu-xenial
    version: "315.61"
  url: https://confluent-platform-bosh-release.s3.amazonaws.com/bpm/bpm-release-1.1.0.tgz
  version: 1.1.0
- name: confluent-platform
  stemcell:
    os: ubuntu-xenial
    version: "315.61"
  version: 5.3.0