---
name: confluent-platform-dev
addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: confluent-platform
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 4
    ram: 8192
    ephemeral_disk_size: 10_000
  vm_extensions:
  - control-center 
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  jobs:
  - name: confluent-zookeeper
    release: confluent-platform
    properties: {}
  - name: confluent-server
    release: confluent-platform
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
      metric_reporter:
        replicas: 1
  - name: confluent-control-center
    release: confluent-platform
  - name: confluent-schema-registry
    release: confluent-platform
  - name: confluent-connect
    release: confluent-platform
    properties:
      config:
        storage:
          replication_factor: 1
      offset:
        storage:
          replication_factor: 1
      status:
        storage:
          replication_factor: 1
  - name: confluent-ksql
    release: confluent-platform

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 315.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 12142ca9437e48694374876fe0236938e252d1e2
  stemcell:
    os: ubuntu-xenial
    version: "315.61"
  url: https://confluent-platform-bosh-release.s3.amazonaws.com/bpm/bpm-release-1.1.0.tgz
  version: 1.1.0
- name: confluent-platform
  sha1: a1531cd6410a4b9dda2014906cbee633b485a3c7
  stemcell:
    os: ubuntu-xenial
    version: "315.61"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/kafka/kafka-2.2.3-ubuntu-xenial-250.23-20190323-023747-677211024-20190323023753.tgz
  version: 5.2.1