---
processes:
- name: confluent-ksql
  executable: /var/vcap/jobs/confluent-ksql/bin/ctl
  args: [start]
  ephemeral_disk: true
  persistent_disk: true
  env: {}
  limits:
    memory: 1G
    open_files: 1024